### ISSUE TITLE
Problem with MFA accounts

### ISSUE THREAD

**Issue by yassinebelieve** [portaldotjay/UniversalPrint#2]
Hello ! 

I'm totally new in GitHub and I saw your script in reddit.

Wanted to know if the MFA is compatible by deploying it thru intune ?

It returns me an error for my MFA account but if I click on the little window that is showing and select my account it's working perfectly, but I really want to know to have someting that is not showing and completely silent.

Do you think it's possible?

Thanks !!

**Comment by JigSawFr** [comment]
We faced the same problem when trying this script :/

**Comment by portaldotjay** [comment]
The auth request happens on block 32-45. It will attempt to use Integrated Windows auth but will fall back to Interactive auth if IWA doesn't work. If IWA doesn't work, then the user will have to interact. 

IWA has some dependencies that vary from environment to environment. If you have hybrid identities, it could be anything from needing to turn on Seamless SSO, updating AD Connect, turning it on in ADFS, setting trusted sites, etc.

**Comment by yassinebelieve** [comment]
@portaldotjay thanks a lot for your response, I tried with normal account without MFA and it seems you are right, it can be some dependencies in my environemment, do you have recommendations ? I mean my objective is that when I launch your script I don't have any interactive auth, I want the script to take the windows user's account and use it to get the token from azure without asking him to enter his password or other, any link or video is appreciate!!

**Comment by portaldotjay** [comment]
@yassinebelieve, unfortunately, I haven't been able to get that kind of an experience without IWA. I tried for a long time to get the same thing in my environment. Everything I've read points to using Integrated Windows Auth but we also had a couple roadblocks in place before we can utilize that. 

The only other way I can think of to make this happen is to use a service account to connect to the Universal Print API, then list all the printer shares and who it's shared to, then compare that list with the current signed in user and add the matching shares. But this is going to be slower and it isn't the most secure so I'm probably not going to explore that method.
